apiVersion: v1
kind: ConfigMap
metadata:
  namespace: training
  name: "{{ .Values.name }}-{{ .Values.version }}"
data:
  app.conf: |
    name: {{ .Values.name }}
    version: {{ .Values.version }}
    message = {{ .Values.message }}
    color = {{ .Values.color }}
    catMode = {{ .Values.catMode }}
