apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: training
  name: "{{ .Values.name }}-{{ .Values.version }}"
  labels:
    app: "{{ .Values.name }}"
    version: "{{ .Values.version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
      version: "{{ .Values.version }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
        version: "{{ .Values.version }}"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: blue
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          tty: true
          stdin: true
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: my-volume
              mountPath: /app/training-application.conf
              subPath: training-application.conf
      volumes:
        - name: my-volume
          configMap:
            name: "{{ .Values.name }}-{{ .Values.version }}"
