{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: training
  name: "{{ .Values.name }}"
spec:
  selector:
    app: "{{ .Values.name }}"
  ports:
    - name: http
      port: 8080
      targetPort: http
{{- end }}
